# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3299eabea527ef6073e61e407b62ad310ef6d6e1b059489902c666692880e77e7f88e3ab24fd0b2ca1e658727f3b3182ac9e99c82f62f673357389a6f34933c0

test:
  secret_key_base: 2a88eafffa2dc98382b949064fde299559ba1eed3f825c62ce5524ccaaa31743d51c47d9540f0381de8b1052cd2e213df1c3f968061af23d845b16f6a92c8fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
